[package]
name = "mini-apm-admin"
edition.workspace = true
version.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "miniapm-admin"
path = "src/main.rs"

[features]
default = ["sqlite"]
sqlite = ["mini-apm/sqlite"]
postgres = ["mini-apm/postgres"]

[dependencies]
mini-apm = { workspace = true, default-features = false }
rama = { workspace = true }
askama = { workspace = true }
jiff = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
mini-apm = { workspace = true, default-features = false, features = ["test-support"] }
